### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by TheWildJames** [OnePlusOSS/kernel_manifest#1]

**Comment by TheWildJames** [comment]
Hello there, how to I download this manifest? 
I was using repo but thats not working for me in not sure eif I'm doing it right,

Thanks Appreciate it alot!

**Comment by OnePlusOSSAdmin** [comment]
Please refer to https://source.android.com/docs/setup/reference/repo, use repo to download code.

**Comment by TheWildJames** [comment]
git clone https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650

# Get the kernel
echo "Get the kernel..."
cd ./kernel_manifest
repo init -u https://android.googlesource.com/kernel/manifest
mv oneplus12_u.xml .repo/manifests
repo init -m oneplus12_u.xml
repo sync -j$(nproc)

is this correct?

this is similar to how i usually build but im not sure how to do it with these?

also what is the difference between the two different version?

**Comment by OnePlusOSSAdmin** [comment]
repo init -u https://github.com/OnePlusOSS/kernel_manifest -b oneplus/sm8650 -m xx.xml

**Comment by TheWildJames** [comment]
running that gives me this 
error: Cannot fetch android_kernel_oneplus_sm8650 from https://github.com/OnePlusOSS/android_kernel_oneplus_sm8650

**Comment by OnePlusOSSAdmin** [comment]
Network connect iusse, just retry

**Comment by TheWildJames** [comment]
been try all night im not sure why i get this error

**Comment by TheWildJames** [comment]
fatal: couldn't find remote ref refs/heads/github_opensource/oneplus/sm8650_u_14.0.0_oneplus12

android_kernel_oneplus_sm8650:
fatal: couldn't find remote ref refs/heads/github_opensource/oneplus/sm8650_u_14.0.0_oneplus12
android_kernel_oneplus_sm8650: sleeping 4.0 seconds before retrying
fatal: couldn't find remote ref refs/heads/github_opensource/oneplus/sm8650_u_14.0.0_oneplus12
error: Cannot fetch android_kernel_oneplus_sm8650 from https://github.com/OnePlusOSS/android_kernel_oneplus_sm8650


this is all a connection issue? ive been using github no problems

**Comment by OnePlusOSSAdmin** [comment]
> fatal: couldn't find remote ref refs/heads/github_opensource/oneplus/sm8650_u_14.0.0_oneplus12
> 
> android_kernel_oneplus_sm8650: fatal: couldn't find remote ref refs/heads/github_opensource/oneplus/sm8650_u_14.0.0_oneplus12 android_kernel_oneplus_sm8650: sleeping 4.0 seconds before retrying fatal: couldn't find remote ref refs/heads/github_opensource/oneplus/sm8650_u_14.0.0_oneplus12 error: Cannot fetch android_kernel_oneplus_sm8650 from https://github.com/OnePlusOSS/android_kernel_oneplus_sm8650
> 
> this is all a connection issue? ive been using github no problems

branch name is wrong, we'll fix it.
`  <project remote="origin" name="android_kernel_oneplus_sm8650" path="kernel_platform/msm-kernel" revision="oneplus/sm8650_u_14.0.0_oneplus12">`

**Comment by TheWildJames** [comment]
awesome ill try again when i see the commit

**Comment by TheWildJames** [comment]
whats the difference from u or v manifest 


edit:
u is a14
v is a15

**Comment by TheWildJames** [comment]
kernel_platform/oplus/build/oplus_setup.sh: line 12: vendor/oplus/kernel/prebuilt/vendorsetup.sh: No such file or directory

my next building error

**Comment by OnePlusOSSAdmin** [comment]
> kernel_platform/oplus/build/oplus_setup.sh: line 12: vendor/oplus/kernel/prebuilt/vendorsetup.sh: No such file or directory
> 
> my next building error

ignore this, it doesn't affect build. all symblinks are already included in code.

**Comment by TheWildJames** [comment]
Awesome kernel built and working! Any plays on uploading the OnePlus 11 manifest?

**Comment by TheWildJames** [comment]
how do i remove the dirty flag? it seems to stay after editing both bazel stamp and setlocalversion
